[2025-08-19T09:53:24.136+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T09:53:24.179+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.data_pull_task manual__2025-08-19T09:53:20.171326+00:00 [queued]>
[2025-08-19T09:53:24.195+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.data_pull_task manual__2025-08-19T09:53:20.171326+00:00 [queued]>
[2025-08-19T09:53:24.197+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-19T09:53:24.223+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_pull_task> on 2025-08-19 09:53:20.171326+00:00
[2025-08-19T09:53:24.249+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=154) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T09:53:24.255+0000] {standard_task_runner.py:63} INFO - Started process 157 to run task
[2025-08-19T09:53:24.254+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'data_pull_task', 'manual__2025-08-19T09:53:20.171326+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/Assessment_2/data_audit_dag.py', '--cfg-path', '/tmp/tmpc1wwoflx']
[2025-08-19T09:53:24.262+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask data_pull_task
[2025-08-19T09:53:24.433+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.data_pull_task manual__2025-08-19T09:53:20.171326+00:00 [running]> on host 37fc8edea13d
[2025-08-19T09:53:24.748+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='rajpriyavondillin1105@gmail.com' AIRFLOW_CTX_DAG_OWNER='rajpriya' AIRFLOW_CTX_DAG_ID='data_audit_dag' AIRFLOW_CTX_TASK_ID='data_pull_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T09:53:20.171326+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T09:53:20.171326+00:00'
[2025-08-19T09:53:24.753+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T09:53:24.756+0000] {logging_mixin.py:188} INFO - [Pull] Pulled Data: {'user_id': 101, 'balance': 115, 'timestamp': '2025-08-19 09:53:24.756569'}
[2025-08-19T09:53:24.758+0000] {python.py:237} INFO - Done. Returned value was: {'user_id': 101, 'balance': 115, 'timestamp': '2025-08-19 09:53:24.756569'}
[2025-08-19T09:53:24.759+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T09:53:24.811+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_audit_dag, task_id=data_pull_task, run_id=manual__2025-08-19T09:53:20.171326+00:00, execution_date=20250819T095320, start_date=20250819T095324, end_date=20250819T095324
[2025-08-19T09:53:24.918+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T09:53:24.974+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
