[2025-08-19T10:40:44.714+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T10:40:44.757+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.validate_audit_task scheduled__2025-08-19T09:00:00+00:00 [queued]>
[2025-08-19T10:40:44.771+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.validate_audit_task scheduled__2025-08-19T09:00:00+00:00 [queued]>
[2025-08-19T10:40:44.773+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-19T10:40:44.797+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): validate_audit_task> on 2025-08-19 09:00:00+00:00
[2025-08-19T10:40:44.814+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=716) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T10:40:44.823+0000] {standard_task_runner.py:63} INFO - Started process 720 to run task
[2025-08-19T10:40:44.821+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'validate_audit_task', 'scheduled__2025-08-19T09:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/Assessment_2/data_audit_dag.py', '--cfg-path', '/tmp/tmpv636dp2e']
[2025-08-19T10:40:44.829+0000] {standard_task_runner.py:91} INFO - Job 51: Subtask validate_audit_task
[2025-08-19T10:40:45.231+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.validate_audit_task scheduled__2025-08-19T09:00:00+00:00 [running]> on host 37fc8edea13d
[2025-08-19T10:40:46.051+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@example.com' AIRFLOW_CTX_DAG_OWNER='rajpriya' AIRFLOW_CTX_DAG_ID='data_audit_dag' AIRFLOW_CTX_TASK_ID='validate_audit_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-19T09:00:00+00:00'
[2025-08-19T10:40:46.063+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T10:40:46.128+0000] {logging_mixin.py:188} INFO - [Audit] Validation result saved: {'data': {'user_id': 101, 'balance': 1247, 'timestamp': '2025-08-19 10:40:37.377351'}, 'valid': True}
[2025-08-19T10:40:46.129+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-19T10:40:46.131+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T10:40:46.158+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_audit_dag, task_id=validate_audit_task, run_id=scheduled__2025-08-19T09:00:00+00:00, execution_date=20250819T090000, start_date=20250819T104044, end_date=20250819T104046
[2025-08-19T10:40:46.258+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T10:40:46.326+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-19T10:40:46.332+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
