[2025-08-19T09:53:19.615+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T09:53:19.646+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.log_results_task manual__2025-08-19T09:53:01.624546+00:00 [queued]>
[2025-08-19T09:53:19.657+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.log_results_task manual__2025-08-19T09:53:01.624546+00:00 [queued]>
[2025-08-19T09:53:19.658+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-19T09:53:19.676+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): log_results_task> on 2025-08-19 09:53:01.624546+00:00
[2025-08-19T09:53:19.691+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=151) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T09:53:19.694+0000] {standard_task_runner.py:63} INFO - Started process 153 to run task
[2025-08-19T09:53:19.695+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'log_results_task', 'manual__2025-08-19T09:53:01.624546+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/Assessment_2/data_audit_dag.py', '--cfg-path', '/tmp/tmpvyzjo05o']
[2025-08-19T09:53:19.698+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask log_results_task
[2025-08-19T09:53:19.780+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.log_results_task manual__2025-08-19T09:53:01.624546+00:00 [running]> on host 37fc8edea13d
[2025-08-19T09:53:19.934+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='rajpriyavondillin1105@gmail.com' AIRFLOW_CTX_DAG_OWNER='rajpriya' AIRFLOW_CTX_DAG_ID='data_audit_dag' AIRFLOW_CTX_TASK_ID='log_results_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T09:53:01.624546+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T09:53:01.624546+00:00'
[2025-08-19T09:53:19.937+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T09:53:19.939+0000] {logging_mixin.py:188} INFO - [Log] Audit Result: {'data': {'user_id': 101, 'balance': 922, 'timestamp': '2025-08-19 09:53:13.201827'}, 'valid': True}
[2025-08-19T09:53:19.940+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-19T09:53:19.942+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T09:53:19.959+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_audit_dag, task_id=log_results_task, run_id=manual__2025-08-19T09:53:01.624546+00:00, execution_date=20250819T095301, start_date=20250819T095319, end_date=20250819T095319
[2025-08-19T09:53:20.031+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T09:53:20.068+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-19T09:53:20.072+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
