[2025-08-19T09:48:06.470+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T09:48:06.528+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.bash_notify_task manual__2025-08-19T09:22:15.873297+00:00 [queued]>
[2025-08-19T09:48:06.547+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.bash_notify_task manual__2025-08-19T09:22:15.873297+00:00 [queued]>
[2025-08-19T09:48:06.549+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-19T09:48:06.582+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): bash_notify_task> on 2025-08-19 09:22:15.873297+00:00
[2025-08-19T09:48:06.606+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T09:48:06.612+0000] {standard_task_runner.py:63} INFO - Started process 81 to run task
[2025-08-19T09:48:06.611+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'bash_notify_task', 'manual__2025-08-19T09:22:15.873297+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/Assessment_2/data_audit_dag.py', '--cfg-path', '/tmp/tmp5gou5gys']
[2025-08-19T09:48:06.618+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask bash_notify_task
[2025-08-19T09:48:06.802+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.bash_notify_task manual__2025-08-19T09:22:15.873297+00:00 [running]> on host 37fc8edea13d
[2025-08-19T09:48:07.069+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@example.com' AIRFLOW_CTX_DAG_OWNER='rajpriya' AIRFLOW_CTX_DAG_ID='data_audit_dag' AIRFLOW_CTX_TASK_ID='bash_notify_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T09:22:15.873297+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T09:22:15.873297+00:00'
[2025-08-19T09:48:07.076+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T09:48:07.080+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-19T09:48:07.085+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Audit DAG run completed!'"]
[2025-08-19T09:48:07.124+0000] {subprocess.py:86} INFO - Output:
[2025-08-19T09:48:07.145+0000] {subprocess.py:93} INFO - Audit DAG run completed!
[2025-08-19T09:48:07.149+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-19T09:48:07.153+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T09:48:07.226+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_audit_dag, task_id=bash_notify_task, run_id=manual__2025-08-19T09:22:15.873297+00:00, execution_date=20250819T092215, start_date=20250819T094806, end_date=20250819T094807
[2025-08-19T09:48:07.317+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T09:48:07.354+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-19T09:48:07.358+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
