[2025-08-19T10:40:44.707+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T10:40:44.753+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.validate_audit_task manual__2025-08-19T10:40:14.119654+00:00 [queued]>
[2025-08-19T10:40:44.768+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.validate_audit_task manual__2025-08-19T10:40:14.119654+00:00 [queued]>
[2025-08-19T10:40:44.770+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-19T10:40:44.792+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): validate_audit_task> on 2025-08-19 10:40:14.119654+00:00
[2025-08-19T10:40:44.815+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=717) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T10:40:44.825+0000] {standard_task_runner.py:63} INFO - Started process 721 to run task
[2025-08-19T10:40:44.825+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'validate_audit_task', 'manual__2025-08-19T10:40:14.119654+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/Assessment_2/data_audit_dag.py', '--cfg-path', '/tmp/tmp9kim2awu']
[2025-08-19T10:40:44.830+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask validate_audit_task
[2025-08-19T10:40:45.266+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.validate_audit_task manual__2025-08-19T10:40:14.119654+00:00 [running]> on host 37fc8edea13d
[2025-08-19T10:40:46.125+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@example.com' AIRFLOW_CTX_DAG_OWNER='rajpriya' AIRFLOW_CTX_DAG_ID='data_audit_dag' AIRFLOW_CTX_TASK_ID='validate_audit_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T10:40:14.119654+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T10:40:14.119654+00:00'
[2025-08-19T10:40:46.136+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T10:40:46.175+0000] {logging_mixin.py:188} INFO - [Audit] Validation result saved: {'data': {'user_id': 101, 'balance': 1061, 'timestamp': '2025-08-19 10:40:37.307630'}, 'valid': True}
[2025-08-19T10:40:46.176+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-19T10:40:46.178+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T10:40:46.212+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_audit_dag, task_id=validate_audit_task, run_id=manual__2025-08-19T10:40:14.119654+00:00, execution_date=20250819T104014, start_date=20250819T104044, end_date=20250819T104046
[2025-08-19T10:40:46.292+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T10:40:46.364+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-19T10:40:46.370+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
