[2025-08-19T09:16:52.502+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T09:16:52.585+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.data_pull_task scheduled__2025-08-19T08:00:00+00:00 [queued]>
[2025-08-19T09:16:52.604+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.data_pull_task scheduled__2025-08-19T08:00:00+00:00 [queued]>
[2025-08-19T09:16:52.606+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-19T09:16:52.637+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_pull_task> on 2025-08-19 08:00:00+00:00
[2025-08-19T09:16:52.661+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2093) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T09:16:52.665+0000] {standard_task_runner.py:63} INFO - Started process 2100 to run task
[2025-08-19T09:16:52.665+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'data_pull_task', 'scheduled__2025-08-19T08:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/data_audit_dag.py', '--cfg-path', '/tmp/tmpoxqtxmiq']
[2025-08-19T09:16:52.671+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask data_pull_task
[2025-08-19T09:16:52.828+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.data_pull_task scheduled__2025-08-19T08:00:00+00:00 [running]> on host 37fc8edea13d
[2025-08-19T09:16:53.851+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@example.com' AIRFLOW_CTX_DAG_OWNER='rajpriya' AIRFLOW_CTX_DAG_ID='data_audit_dag' AIRFLOW_CTX_TASK_ID='data_pull_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-19T08:00:00+00:00'
[2025-08-19T09:16:53.871+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T09:16:53.874+0000] {logging_mixin.py:188} INFO - [Pull] Pulled Data: {'user_id': 101, 'balance': 1461, 'timestamp': '2025-08-19 09:16:53.873915'}
[2025-08-19T09:16:53.875+0000] {python.py:237} INFO - Done. Returned value was: {'user_id': 101, 'balance': 1461, 'timestamp': '2025-08-19 09:16:53.873915'}
[2025-08-19T09:16:53.877+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T09:16:55.427+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_audit_dag, task_id=data_pull_task, run_id=scheduled__2025-08-19T08:00:00+00:00, execution_date=20250819T080000, start_date=20250819T091652, end_date=20250819T091655
[2025-08-19T09:16:55.540+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T09:16:55.784+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-19T09:16:55.790+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
