[2025-08-19T09:24:40.785+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T09:24:40.925+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.validate_audit_task scheduled__2025-08-19T08:00:00+00:00 [queued]>
[2025-08-19T09:24:40.956+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.validate_audit_task scheduled__2025-08-19T08:00:00+00:00 [queued]>
[2025-08-19T09:24:40.958+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-19T09:24:41.010+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): validate_audit_task> on 2025-08-19 08:00:00+00:00
[2025-08-19T09:24:41.072+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2169) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T09:24:41.080+0000] {standard_task_runner.py:63} INFO - Started process 2177 to run task
[2025-08-19T09:24:41.077+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'validate_audit_task', 'scheduled__2025-08-19T08:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/Assessment_2/data_audit_dag.py', '--cfg-path', '/tmp/tmphq_z46jx']
[2025-08-19T09:24:41.089+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask validate_audit_task
[2025-08-19T09:24:41.334+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.validate_audit_task scheduled__2025-08-19T08:00:00+00:00 [running]> on host 37fc8edea13d
[2025-08-19T09:24:41.689+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@example.com' AIRFLOW_CTX_DAG_OWNER='rajpriya' AIRFLOW_CTX_DAG_ID='data_audit_dag' AIRFLOW_CTX_TASK_ID='validate_audit_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-19T08:00:00+00:00'
[2025-08-19T09:24:41.714+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T09:24:41.771+0000] {logging_mixin.py:188} INFO - [Audit] Validation result saved: {'data': {'user_id': 101, 'balance': 1461, 'timestamp': '2025-08-19 09:16:53.873915'}, 'valid': True}
[2025-08-19T09:24:41.775+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-19T09:24:41.777+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T09:24:41.835+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_audit_dag, task_id=validate_audit_task, run_id=scheduled__2025-08-19T08:00:00+00:00, execution_date=20250819T080000, start_date=20250819T092440, end_date=20250819T092441
[2025-08-19T09:24:41.950+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T09:24:42.073+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-19T09:24:42.078+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
